import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import "remixicon/fonts/remixicon.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import DVContainer from "@/components/DVContainer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "KZT's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${poppins.variable} text-white bg-black`}>
        <div style={{ width: "100%", height: "600px", position: "relative" }}>
          <DVContainer />
          <Navbar />
          <TooltipProvider>
            <main className="overflow-hidden pb-20">{children}</main>
          </TooltipProvider>
        </div>
      </body>
    </html>
  );
}
