import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import DarkVeil from "@/components/DarkVeil";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "KZT's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${poppins.variable} text-white`}>
        <div style={{ width: "100%", height: "600px", position: "relative" }}>
          <DarkVeil />
          <Navbar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
